services:
  db:
    container_name: nestjs_basedb
    image: postgres:9.3
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD:  ${DB_PASSWORD} 
      POSTGRES_DB: ${BD_NAME} 
    ports:
      - "5432:5432"